/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root;

import Palabras.Ingles_Español;
import clases.Conector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar Medellin
 */
public class root_Expresiones extends javax.swing.JFrame {

    /**
     * Creates new form root_Expresiones
     */
    public root_Expresiones() {
        initComponents();
        mostrarExpresiones("");
    }
public void mostrarExpresiones(String valor){
     DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("CODIGO");
    modelo.addColumn("EXPRESION");
    modelo.addColumn("SIGNIFICADO");
    modelo.addColumn("EJEMPLO INGLES");
    modelo.addColumn("EJEMPLO ESPAÑOL");
    tabla_root_expresiones.setModel(modelo);
    String sql="";
     if(valor.equals(""))
    {
        sql="SELECT * FROM Expresiones_Ideomaticas";
    }
    else{
        sql="SELECT * FROM Expresiones_Ideomaticas WHERE Expresiones='"+valor+"'";
    }
    String []datos = new String [5];
        try {
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                
                modelo.addRow(datos);
            }
            tabla_root_expresiones.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(root_Expresiones.class.getName()).log(Level.SEVERE, null, ex);
        }
}public void Limpiar(){ 
     txt_codigoE.setText(null);
     txt_expresionE.setText(null);
     txt_significadoE.setText(null);
     txt_ejemplo_inglesE.setText(null);
     txt_ejemplo_españolE.setText(null);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        modificar = new javax.swing.JMenuItem();
        eliminar2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_root_expresiones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_codigoE = new javax.swing.JTextField();
        txt_expresionE = new javax.swing.JTextField();
        txt_significadoE = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ejemplo_inglesE = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_ejemplo_españolE = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        modificar.setText("jMenuItem1");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar2.setText("jMenu1");
        eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Root Insertar, modificar y eliminar expresiones");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_root_expresiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_root_expresiones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla_root_expresiones.setComponentPopupMenu(jPopupMenu2);
        jScrollPane1.setViewportView(tabla_root_expresiones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, 1260, 170));

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setText("Expresión :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Significado :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("Ejemplo en Ingles :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel5.setText("Ejemplo en Español :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));
        getContentPane().add(txt_codigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 170, -1));
        getContentPane().add(txt_expresionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 160, -1));
        getContentPane().add(txt_significadoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        txt_ejemplo_inglesE.setColumns(20);
        txt_ejemplo_inglesE.setRows(5);
        jScrollPane2.setViewportView(txt_ejemplo_inglesE);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 320, 100));

        txt_ejemplo_españolE.setColumns(20);
        txt_ejemplo_españolE.setRows(5);
        jScrollPane3.setViewportView(txt_ejemplo_españolE);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 320, 100));

        jLabel6.setText("Ingresar, modificar y eliminar expresiones ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
        PreparedStatement pst = cn.prepareStatement("INSERT INTO Expresiones_Ideomaticas (CodEI,Expresion,Significados,Ejemplo_Ingles,Ejemplo_Español) VALUES (?,?,?,?,?)");
        pst.setString(1, txt_codigoE.getText());
        pst.setString(2, txt_expresionE.getText());
        pst.setString(3, txt_significadoE.getText());
        pst.setString(4, txt_ejemplo_inglesE.getText());
        pst.setString(5, txt_ejemplo_españolE.getText());
        pst.executeUpdate();
       
      mostrarExpresiones("");
      Limpiar();
    } catch (Exception e) {
        System.out.print(e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          try {
        PreparedStatement pst = cn.prepareStatement("UPDATE Expresiones_Ideomaticas SET Ejemplo_Español='"+txt_codigoE.getText()+"',Ejemplo_Ingles='"+txt_ejemplo_inglesE.getText()+"',Significados='"+txt_significadoE.getText()+"',Expresion='"+txt_expresionE.getText()+"' WHERE CodEI='"+txt_codigoE.getText()+"'");
        pst.executeUpdate();
        mostrarExpresiones("");
        Limpiar();
    } catch (Exception e) {
        System.out.print(e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar2ActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_eliminar2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                int fila = tabla_root_expresiones.getSelectedRow();
    String codEI="";
    codEI=tabla_root_expresiones.getValueAt(fila, 0).toString();
    
    try {
        PreparedStatement pst = cn.prepareStatement("DELETE FROM Expresiones_Ideomaticas WHERE  CodEI='"+codEI+"'");
        pst.executeUpdate();
        mostrarExpresiones("");
    } catch (Exception e) {
    }
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            int fila = tabla_root_expresiones.getSelectedRow();
    String codEI="";
    codEI=tabla_root_expresiones.getValueAt(fila, 0).toString();
    
    try {
        PreparedStatement pst = cn.prepareStatement("DELETE FROM Expresiones_Ideomaticas WHERE  CodEI='"+codEI+"'");
        pst.executeUpdate();
        mostrarExpresiones("");
    } catch (Exception e) {
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(root_Expresiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(root_Expresiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(root_Expresiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(root_Expresiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new root_Expresiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu eliminar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JTable tabla_root_expresiones;
    private javax.swing.JTextField txt_codigoE;
    private javax.swing.JTextArea txt_ejemplo_españolE;
    private javax.swing.JTextArea txt_ejemplo_inglesE;
    private javax.swing.JTextField txt_expresionE;
    private javax.swing.JTextField txt_significadoE;
    // End of variables declaration//GEN-END:variables
Conector cc= new Conector();
    Connection cn= cc.conexion();
}
